name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
          cache: gradle

      - name: Create key.jks
        run: echo ${{ secrets.KEY_BASE64 }} | base64 --decode > key.jks

      - name: Create local.properties
        run: echo APP_CENTER_SECRET=${{ secrets.APP_CENTER_SECRET }} > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3.1.1
        with:
          path: ./app/build/outputs/apk/release/


  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Get APK file path
        run: |
          apk_path=$(find ./artifact/*.apk -type f | head -1)
          echo "APK_PATH=$apk_path" >> $GITHUB_ENV

      - name: Upload APK to App Center
        uses: wzieba/AppCenter-Github-Action@v1.3.3
        with:
          appName: bqliang/Leave-Sheet
          group: public
          token: ${{ secrets.APP_CENTER_TOKEN }}
          file: ${{ env.APK_PATH }}

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.APK_PATH }}
          generateReleaseNotes: true